FROM python:3.11
LABEL maintainer="akinolawilson@gmail.com"

WORKDIR /usr/src/app
RUN pip install --upgrade pip 
COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt 

RUN mkdir core heed
COPY ./core ./core 
COPY ./heed ./heed  
COPY ./manage.py ./ 
# runs on port 8000 
ENTRYPOINT [ "python","manage.py","runserver", "0.0.0.0:8000" ]